## 异常分类
* Error错误：JVM系统错误，比如资源耗尽等，开发对其不处理，当程序发生不可控的错误时，通常做法是通知用户并中止程序的执行；
* Exception异常：
    * RuntimeException：非受检异常(unchecked exception)，（extends RuntimeException），这类异常是编程人员的逻辑问题，编译器不强制要求处理
    * 非RuntimeException：受检异常(checked exception)，（extends Exception），在编译时期有编译器检测的异常,必须要处理异常（要么被catch,要么被throw）

### 常见的unchecked exception
* NullPointerException
* ClassCastException
* IndexsOutOfBoundsException
* ArithmeticException

### 常见的checked exception
* Exception
* FileNotFoundException
* IOException
* SQLException

## 抛出异常还是return false?
1. 异常是不在预期范围内的，而错误是在预期范围内的，比如用户输入密码错误，这个就不是异常，而是错误值；
2. 一般业务逻辑更多的是错误值（return false），而异常更多的是技术非预期，比如类型错误，连接失败等；

## try-with-resource自动关闭资源
更优雅的关闭资源的写法，不需要通过try-catch-finally关闭资源，减少代码复杂度。    
其原理是编译器自动帮我们生成了fianlly并调用了close方法关闭资源；
```java
        try (BufferedInputStream bin = new BufferedInputStream(new FileInputStream(new File("test.txt")));
             BufferedOutputStream bout = new BufferedOutputStream(new FileOutputStream(new File("out.txt")))) {
            int b;
            while ((b = bin.read()) != -1) {
                bout.write(b);
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }
```

为了能够配合try-with-resource，资源必须实现AutoClosable接口。该接口的实现类需要重写close方法：
```java
public class Connection implements AutoCloseable {
    public void sendData() {
        System.out.println("正在发送数据");
    }
    @Override
    public void close() throws Exception {
        System.out.println("正在关闭连接");
    }
}
```


## 参考
* [深入理解Java try-with-resource](https://zhuanlan.zhihu.com/p/27824934)

